import {
  Bug,
  CalendarClock,
  Database,
  FileCode2,
  FileJson2,
  Fingerprint,
  Image,
  KeyRound,
  Link2,
  QrCode,
  RadioTower,
  Regex,
  ShieldCheck,
} from 'lucide-react';

export const categories = [
  { id: 'all', label: '全部' },
  { id: 'format', label: '格式化' },
  { id: 'encode', label: '编码转换' },
  { id: 'dev', label: '开发调试' },
  { id: 'media', label: '图片文件' },
  { id: 'suite', label: '工具合集' },
];

export const tools = [
  {
    id: 'json-lab',
    name: 'JSON 工作台',
    category: 'format',
    route: '/tools/json-lab',
    description: '格式化、压缩、结构统计',
    status: 'ready',
    backend: false,
    icon: FileJson2,
    accent: 'green',
    inputs: ['文本'],
    outputs: ['结构树', 'Diff'],
  },
  {
    id: 'regex-checker',
    name: '正则校验器',
    category: 'dev',
    route: '/tools/regex-checker',
    description: '表达式测试、匹配位置、Flags 调试',
    status: 'ready',
    backend: false,
    icon: Regex,
    accent: 'violet',
    inputs: ['Pattern', 'Sample'],
    outputs: ['Match'],
  },
  {
    id: 'java-error-analyzer',
    name: 'Java 报错分析',
    category: 'dev',
    route: '/tools/java-error-analyzer',
    description: '异常堆栈、Root cause、修复建议',
    status: 'ready',
    backend: false,
    icon: Bug,
    accent: 'cyan',
    inputs: ['Stacktrace'],
    outputs: ['Report'],
  },
  {
    id: 'jwt-inspector',
    name: 'JWT 解析器',
    category: 'encode',
    route: '/tools/jwt-inspector',
    description: 'Header、Payload、过期时间解析',
    status: 'ready',
    backend: false,
    icon: KeyRound,
    accent: 'orange',
    inputs: ['Token'],
    outputs: ['Claims'],
  },
  {
    id: 'url-codec',
    name: 'URL 编解码',
    category: 'encode',
    route: '/tools/url-codec',
    description: 'URL、Base64、HTML 实体转换',
    status: 'ready',
    backend: false,
    icon: Link2,
    accent: 'blue',
    inputs: ['文本'],
    outputs: ['结果'],
  },
  {
    id: 'api-console',
    name: '接口调试台',
    category: 'dev',
    route: '/tools/api-console',
    description: '请求代理、响应查看、环境变量',
    status: 'backend',
    backend: true,
    icon: RadioTower,
    accent: 'cyan',
    inputs: ['HTTP'],
    outputs: ['Response'],
  },
  {
    id: 'sql-helper',
    name: 'SQL 助手',
    category: 'dev',
    route: '/tools/sql-helper',
    description: 'SQL 格式化、Explain 记录、字段映射',
    status: 'planned',
    backend: true,
    icon: Database,
    accent: 'yellow',
    inputs: ['SQL'],
    outputs: ['Plan'],
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    category: 'format',
    route: '/tools/timestamp',
    description: '秒毫秒识别、本地时间、UTC 预览',
    status: 'ready',
    backend: false,
    icon: CalendarClock,
    accent: 'red',
    inputs: ['Timestamp'],
    outputs: ['Date'],
  },
  {
    id: 'hash-lab',
    name: '哈希摘要',
    category: 'encode',
    route: '/tools/hash-lab',
    description: 'SHA-1、SHA-256、SHA-384、SHA-512',
    status: 'ready',
    backend: false,
    icon: Fingerprint,
    accent: 'indigo',
    inputs: ['文本', '文件'],
    outputs: ['Hash'],
  },
  {
    id: 'image-compress',
    name: '图片压缩',
    category: 'media',
    route: '/tools/image-compress',
    description: '批量上传、自动压缩、ZIP 下载',
    status: 'ready',
    backend: false,
    icon: Image,
    accent: 'pink',
    inputs: ['图片队列'],
    outputs: ['压缩包'],
  },
  {
    id: 'qr-maker',
    name: '二维码生成',
    category: 'media',
    route: '/tools/qr-maker',
    description: '文本、链接、配色、Logo 嵌入',
    status: 'planned',
    backend: false,
    icon: QrCode,
    accent: 'teal',
    inputs: ['文本'],
    outputs: ['PNG'],
  },
  {
    id: 'mega-tools-suite',
    name: '50工具合集',
    category: 'suite',
    route: '/tools/mega-tools-suite',
    description: '合并自在线工具合集项目，含50个浏览器本地工具',
    status: 'ready',
    backend: false,
    icon: FileCode2,
    accent: 'blue',
    inputs: ['文本', '文件'],
    outputs: ['转换结果'],
  },
  {
    id: 'diff-viewer',
    name: '文本对比',
    category: 'format',
    route: '/tools/diff-viewer',
    description: '双向三向、差异导航、行内高亮',
    status: 'ready',
    backend: false,
    icon: FileCode2,
    accent: 'gray',
    inputs: ['左', '右'],
    outputs: ['Diff'],
  },
  {
    id: 'cert-reader',
    name: '证书查看器',
    category: 'ops',
    route: '/tools/cert-reader',
    description: '证书链、有效期、域名与指纹',
    status: 'backend',
    backend: true,
    icon: ShieldCheck,
    accent: 'lime',
    inputs: ['Host', 'PEM'],
    outputs: ['Cert'],
  },
];
